### ISSUE TITLE
 Project name not set. Call init() first.

### ISSUE THREAD

**Issue by mohammadhunan-dev** [mayooear/notion-chat-langchain#4]
Hey, I'm getting the following error when trying to npm run `ingest`:

```
/notion-chat-langchain/node_modules/@pinecone-database/pinecone/dist/index.js:172
            throw new Error('PineconeClient: Project name not set. Call init() first.');
                  ^

Error: PineconeClient: Project name not set. Call init() first.
    at PineconeClient2.PineconeClient2.Index (/notion-chat-langchain/node_modules/@pinecone-database/pinecone/dist/index.js:172:19)
    at null.run (/notion-chat-langchain/scripts/ingest-data.ts:28:28)
    at null.<anonymous> (/notion-chat-langchain/scripts/ingest-data.ts:43:3)
(node:96491) UnhandledPromiseRejectionWarning: /notion-chat-langchain/scripts/ingest-data.ts:38
    throw new Error('Failed to ingest your data');
          ^
```
I've updated the .env with the correct credentials. Perhap this is an issue with incorrect API implementation?

**Comment by shynsky** [comment]
@mongomoe - Maybe paste a structure (without actual values) of your .env file here.

**Comment by roulendz** [comment]
> Hey, I'm getting the following error when trying to npm run `ingest`:
> 
> ```
> /notion-chat-langchain/node_modules/@pinecone-database/pinecone/dist/index.js:172
>             throw new Error('PineconeClient: Project name not set. Call init() first.');
>                   ^
> 
> Error: PineconeClient: Project name not set. Call init() first.
>     at PineconeClient2.PineconeClient2.Index (/notion-chat-langchain/node_modules/@pinecone-database/pinecone/dist/index.js:172:19)
>     at null.run (/notion-chat-langchain/scripts/ingest-data.ts:28:28)
>     at null.<anonymous> (/notion-chat-langchain/scripts/ingest-data.ts:43:3)
> (node:96491) UnhandledPromiseRejectionWarning: /notion-chat-langchain/scripts/ingest-data.ts:38
>     throw new Error('Failed to ingest your data');
>           ^
> ```
> 
> I've updated the .env with the correct credentials. Perhap this is an issue with incorrect API implementation?

in package.json chhange
```
"@pinecone-database/pinecone": "0.0.10",
```
and then run 

```
npm install
```
this should fix the isshue
